services:
  prover:
    image: whoami39/cysic-prover
    container_name: prover
    environment:
      - EVM_ADDR="<your-evm-address>"
    volumes:
      - ./data/data:/app/data
      - ./data/cysic/:/root/.cysic/
      - ./data/scroll_prover:/root/.scroll_prover
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: ["gpu"]
    network_mode: "host"
    restart: unless-stopped